cfg/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls', namespace='mailings')),
    path('', include('users.urls', namespace='users')),
    path('', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path

from mailings.views import CreateMailingView, ListMailingView, UpdateMailingView, DeleteMailingView, \
    DetailMailingView, CreateClientView, ListClientView, DeleteClientView, MailingLogListView, DeleteMailingLogView, \
    DetailMailingLogView, DetailClientView, UpdateClientView, CreateMessageView, ListMessageView, UpdateMessageView, \
    DeleteMessageView, DetailMessageView

app_name = 'mailings'

urlpatterns = [
    path('mailing/create', CreateMailingView.as_view(), name='create_mailing'),
    path('mailing/list', ListMailingView.as_view(), name='list_mailing'),
    path('mailing/update/<int:pk>/', UpdateMailingView.as_view(), name='update_mailing'),
    path('mailing/delete/<int:pk>/', DeleteMailingView.as_view(), name='delete_mailing'),
    path('mailing/detail/<int:pk>/', DetailMailingView.as_view(), name='detail_mailing'),

    path('client/create/', CreateClientView.as_view(), name='create_client'),
    path('client/list/', ListClientView.as_view(), name='list_client'),
    path('client/update/<int:pk>/', UpdateClientView.as_view(), name='update_client'),
    path('client/detail/<int:pk>/', DetailClientView.as_view(), name='detail_client'),
    path('client/delete/<int:pk>/', DeleteClientView.as_view(), name='delete_client'),

    path('message/create/', CreateMessageView.as_view(), name='create_message'),
    path('message/list/', ListMessageView.as_view(), name='list_message'),
    path('message/update/<int:pk>/', UpdateMessageView.as_view(), name='update_message'),
    path('message/delete/<int:pk>/', DeleteMessageView.as_view(), name='delete_message'),
    path('message/detail/<int:pk>/', DetailMessageView.as_view(), name='detail_message'),

    path('logs/', MailingLogListView.as_view(), name='mailing_logs_list'),
    path('logs/detail/<int:pk>/', DetailMailingLogView.as_view(), name='mailing_log_detail'),
    path('log/delete/<int:pk>/', DeleteMailingLogView.as_view(), name='delete_mailing_log'),
]

mailings/models.py
from datetime import datetime

from django.conf import settings
from django.db import models

NULLABLE = {'null': True, 'blank': True}


# Create your models here.
class Client(models.Model):
    email = models.EmailField(verbose_name='электронная почта')
    surname = models.CharField(max_length=20, verbose_name='фамилия')
    name = models.CharField(max_length=20, verbose_name='имя')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='пользователь')

    def __str__(self):
        return f'Клиент: {self.email}.'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Message(models.Model):
    mail_subject = models.TextField(max_length=100, verbose_name='тема письма')
    mail_text = models.TextField(verbose_name='тело письма')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='пользователь')

    def __str__(self):
        return f'Сообщение: {self.mail_subject}.'

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Mailing(models.Model):
    FREQUENCY_CHOICES = (
        ('daily', 'Раз в день'),
        ('weekly', 'Раз в неделю'),
        ('monthly', 'Раз в месяц'),
    )

    STATUS_CHOICES = (
        ('created', 'Создана'),
        ('started', 'Запущена'),
        ('completed', 'Завершена'),
    )

    name = models.CharField(max_length=100, verbose_name='название рассылки', default='Новая рассылка')
    mailing_time = models.DateTimeField(verbose_name='время рассылки')
    frequency = models.CharField(max_length=10, choices=FREQUENCY_CHOICES, verbose_name='периодичность')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='created', verbose_name='статус рассылки')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='сообщение', **NULLABLE)
    clients = models.ManyToManyField(Client, related_name='mailings', verbose_name='клиенты')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='пользователь')
    is_active = models.BooleanField(default=True, verbose_name='признак активности')
    is_view = models.BooleanField(default=False, verbose_name='признак просмотра')

    def __str__(self):
        return f'Рассылка {self.name}.'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

    permissions = [
            (
                'set_active',
                'can activate mailings',
            ),
        ]


class MailingLog(models.Model):
    STATUS_CHOICES = (
        ('success', 'Успешно'),
        ('failed', 'Не удалось'),
    )

    timestamp = models.DateTimeField(default=datetime.now, verbose_name='дата и время попытки')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, verbose_name='статус попытки')
    server_response = models.TextField(verbose_name='ответ почтового сервера', **NULLABLE)
    client = models.ManyToManyField(Client, related_name='logs', verbose_name='клиент')
    mailing_list = models.ForeignKey(Mailing, on_delete=models.CASCADE, related_name='logs',
                                     verbose_name='рассылка')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='пользователь')

    def __str__(self):
        return f'Лог: "{self.mailing_list}"'

    class Meta:
        verbose_name = 'Лог рассылки'
        verbose_name_plural = 'Логи рассылок'

mailings/forms.py
from django import forms

from mailings.models import Mailing, Client, Message


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'clients':
                continue
            elif field_name == 'message':
                field.widget.attrs['class'] = 'form-select'
            else:
                field.widget.attrs['class'] = 'form-control'


class CreateMessageForm(StyleFormMixin, forms.ModelForm):
    mail_subject = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Введите текст'}),
        label='Тема сообщения'
    )

    mail_text = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': 'Введите текст'}),
        label='Текст сообщения'
    )

    class Meta:
        model = Message
        fields = ('mail_subject', 'mail_text',)


class CreateMailingForm(StyleFormMixin, forms.ModelForm):
    mailing_time = forms.DateTimeField(
        widget=forms.DateTimeInput(
            attrs={
                'class': 'form-control',
                'type': 'datetime-local'
            }
        ),
        label='Дата и время рассылки'
    )

    clients = forms.ModelMultipleChoiceField(
        queryset=Client.objects.none(),
        widget=forms.CheckboxSelectMultiple,
        label='Клиенты'
    )

    message = forms.ModelChoiceField(
        queryset=Message.objects.none(),
        widget=forms.Select(),
        label='Сообщение'
    )

    class Meta:
        model = Mailing
        exclude = ('status', 'user', 'is_active')

    def __init__(self, user, *args, **kwargs):

        super().__init__(*args, **kwargs)
        self.fields['clients'].queryset = Client.objects.filter(user=user)
        self.fields['message'].queryset = Message.objects.filter(user=user)


class UpdateMailingForm(StyleFormMixin, forms.ModelForm):

    mailing_time = forms.DateTimeField(
        widget=forms.DateTimeInput(
            attrs={
                'class': 'form-control',
                'type': 'datetime-local'
            }
        ),
        label='Дата и время рассылки'
    )

    clients = forms.ModelMultipleChoiceField(
        queryset=Client.objects.none(),
        widget=forms.CheckboxSelectMultiple,
        label='Клиенты'
    )

    message = forms.ModelChoiceField(
        queryset=Message.objects.none(),
        label='Сообщение'
    )

    class Meta:
        model = Mailing
        fields = ('mailing_time', 'frequency', 'clients')

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        self.fields['clients'].queryset = Client.objects.filter(user=user)
        self.fields['message'].queryset = Message.objects.filter(user=user)


class CreateClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        exclude = ('user', )


class ManagerMailingForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ('is_active',)

mailings/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView, ListView

from mailings.forms import CreateMailingForm, UpdateMailingForm, CreateClientForm, CreateMessageForm,\
    ManagerMailingForm
from mailings.models import Mailing, Client, MailingLog, Message


# Create your views here.

@method_decorator(login_required(login_url='users:login'), name='dispatch')
class CreateMailingView(CreateView):
    model = Mailing
    form_class = CreateMailingForm
    success_url = reverse_lazy('mailings:list_mailing')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get(self, request, **kwargs):
        user = self.request.user
        form = self.form_class(self.request.user, request.POST)
        context = {
            'form': form,
        }
        clients = Client.objects.filter(user=user)
        message = Message.objects.filter(user=user)
        context['clients'] = clients
        context['message'] = message
        return render(request, 'mailings/mailing_form.html', context)



    def save_mailing(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            mailing = form.save(commit=False)
            mailing.user = self.request.user
            mailing.save()
            form.save_m2m()
        return redirect(self.success_url)


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class UpdateMailingView(UpdateView):
    model = Mailing
    form_class = UpdateMailingForm
    success_url = reverse_lazy('mailings:list_mailing')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        clients = Client.objects.filter(user=self.request.user)
        context['clients'] = clients
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return UpdateMailingForm
        if user.has_perm('mail.set_active'):
            return ManagerMailingForm
        raise PermissionDenied


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class ListMailingView(ListView):
    model = Mailing
    template_name = 'mailings/mailing_list.html'

    def get_queryset(self):
        return Mailing.objects.filter(user=self.request.user)


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class DetailMailingView(DetailView):
    model = Mailing
    template_name = 'mailings/mailing_detail.html'


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class DeleteMailingView(DeleteView):
    model = Mailing
    template_name = 'mailings/mailing_confirm_delete.html'
    success_url = reverse_lazy('mailings:list_mailing')


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class CreateClientView(CreateView):
    model = Client
    form_class = CreateClientForm
    success_url = reverse_lazy('mailings:list_client')

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            try:
                client = form.save(commit=False)
                client.user = self.request.user
                client.save()
            except ValueError:
                return render(request, 'mailings/client_exists.html')
            else:
                return redirect(self.success_url)


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class UpdateClientView(UpdateView):
    model = Client
    form_class = CreateClientForm
    success_url = reverse_lazy('mailings:list_client')


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['clients'] = Client.objects.filter(user=self.request.user)
        return context


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class ListClientView(ListView):
    model = Client
    template_name = 'mailings/clients_list.html'

    def get_queryset(self):
        return Client.objects.filter(user=self.request.user)


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class DetailClientView(DetailView):
    model = Client
    template_name = 'mailings/client_detail.html'


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class DeleteClientView(DeleteView):
    model = Client
    template_name = 'mailings/client_confirm_delete.html'
    success_url = reverse_lazy('mailings:clients_list')


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class MailingLogListView(ListView):
    model = MailingLog
    template_name = 'mailings/mailing_logs_list.html'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return self.model.objects.all
        else:
            return self.model.objects.filter(user=self.request.user)


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class DetailMailingLogView(DetailView):
    model = MailingLog
    template_name = 'mailings/mailing_log_detail.html'


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class DeleteMailingLogView(DeleteView):
    model = MailingLog
    template_name = 'mailings/log_confirm_delete.html'
    success_url = reverse_lazy('mailings:mailing_logs_list')


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class CreateMessageView(CreateView):
    model = Message
    form_class = CreateMessageForm
    success_url = reverse_lazy('mailings:list_message')

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            message = form.save(commit=False)
            message.user = self.request.user
            message.save()
        return redirect(self.success_url)


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class ListMessageView(ListView):
    model = Message
    template_name = 'mailings/messages_list.html'

    def get_queryset(self):
        return Message.objects.filter(user=self.request.user)


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class UpdateMessageView(UpdateView):
    model = Message
    form_class = CreateMessageForm
    success_url = reverse_lazy('mailings:list_message')


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class DeleteMessageView(DeleteView):
    model = Message
    template_name = 'mailings/message_confirm_delete.html'
    success_url = reverse_lazy('mailings:list_message')


@method_decorator(login_required(login_url='users:login'), name='dispatch')
class DetailMessageView(DetailView):
    model = Message
    template_name = 'mailings/message_detail.html'

templates/mailings/client_confirm_delete.html
{% extends 'index.html' %}

{% block content %}
<div class="col-12">
    <div class="col-md-6 mx-auto">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Хотите удалить пользователя "{{ object.email }}"?</p>
                    <button type="submit" class="btn btn-danger">Подтвердить</button>
                    <a onclick="goBack()" class="btn btn-warning">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
function goBack() {
  window.history.back();
}


</script>
{% endblock %}

templates/mailings/client_detail.html
{% extends 'index.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Клиент рассылки - "{{ object.email }}"
                    </h3>
                    <h3 class="card-title">
                        {% if object.user %}
                            Создатель: @{{ object.user }}
                        {% endif %}
                    </h3>
                </div>
                <div class="card-body">
                    <p>
                        Имя: {{ object.name }}
                    </p>
                    <p>
                        Фамилия: {{ object.surname }}
                    </p>
                </div>
                <div class="card-footer" style="display: flex; justify-content: space-between; align-items: center;">
                    <div class="right-button">
                        <a onclick="goBack()" class="btn btn-warning mt-2">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
function goBack() {
  window.history.back();
}
</script>
{% endblock %}

templates/mailings/clients_list.html
{% extends 'index.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Клиенты</h1>
</div>
<div class="col-12 mb-3">
    <a class="btn btn-outline-primary col-12" href="{% url 'mailings:create_client' %}">Добавить клиента</a>
</div>
<div class="row text-center mt-3">
    {% for object in object_list %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Клиент "{{ object.email }}"</h4>
            </div>
            <div class="card-body">
                   <div class="card-text">ФИ: {{ object.surname }} {{ object.name }}.</div>
                 
                <div class="card-text">Дата рассылки: {{ object.mailing_time }}.</div>
                <a href="{% url 'mailings:detail_client' object.pk %}" type="button"
                   class="btn btn-lg btn-block btn-outline-primary mt-3">Подробнее</a>
                <a href="{% url 'mailings:update_client' object.pk %}" type="button"
                   class="btn btn-lg btn-block btn-outline-warning mt-3">Изменить</a>
                <a href="{% url 'mailings:delete_client' object.pk %}" type="button"
                   class="btn btn-lg btn-block btn-outline-danger mt-3">Удалить</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/mailings/index.html
{% load static %}
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Mail Service</title>
      <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
   </head>
   <body>

      <div class="container">
         {% block content %}
         {% endblock %}
         <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
               <div class="col-12 col-md">
                  Mail Service
                  <small class="d-block mb-3 text-muted">&copy; 2024</small>
               </div>
            </div>
         </footer>
      </div>
      <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
   </body>
</html>

templates/mailings/mailing_confirm_delete.html
{% extends 'mailings/../index.html' %}

{% block content %}
<div class="col-12">
    <div class="col-md-6 mx-auto">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Хотите удалить рассылку "{{ object.mail_theme }}"?</p>
                    <button type="submit" class="btn btn-danger">Подтвердить</button>
                    <a onclick="goBack()" class="btn btn-warning">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
function goBack() {
  window.history.back();
}

</script>
{% endblock %}

templates/mailings/mailing_detail.html
{% extends 'index.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Рассылка "{{ object.mail_subject }}"
                    </h3>
                    <h3 class="card-title">
                        {% if object.user %}
                            Владелец рассылки: @{{ object.user }}
                        {% endif %}
                    </h3>
                </div>
                <div class="card-body">
                    <p>
                        Cообщение: {{ object.mail_text }}
                    </p>
                    <p>
                        Кому:
                        {% for client in mailing.clients.all  %}
                        {{ client.email }};
                        {% endfor %}
                    </p>
                </div>
                <div class="card-footer" style="display: flex; justify-content: space-between; align-items: center;">
                    <div>
                        Дата и время рассылки: {{ object.mailing_time }}
                        {% if object.last_update %}
                        Дата последнего изменения: {{ object.last_update }}
                        {% endif %}
                    </div>
                    <div class="right-button">
                        <a onclick="goBack()" class="btn btn-warning mt-2">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
function goBack() {
  window.history.back();
}
</script>
{% endblock %}

templates/mailings/mailing_form.html
{% extends 'index.html' %}
{% block content %}
<div class="col-12">
   <div class="col-md-6 mx-auto">
      <div class="card">
         {% if object %}
         <div class="card-header">Изменение рассылки "{{ object.mail_subject }}".</div>
         {% else %}
         <div class="card-header">Создание рассылки.</div>
         {% endif %}
         <div class="card-body">
            <form method="post" enctype="multipart/form-data">
               {% csrf_token %}
               {{ form.mailing_time.label_tag }}{{ form.mailing_time }}
               {% if clients.count == 0 %}
               <div class="mt-3">
                  {{ form.clients.label_tag }}
               </div>
               <div class="alert alert-info">
                  Клиенты не обнаружены.
               </div>
               <a href="{% url 'mailings:create_client' %}" class="btn btn-primary">Добавить клиента</a>
               {% else %}
               <div class="mt-3">
                  {{ form.clients.label_tag }}{{ form.clients }}
               </div>
               {% endif %}
               <div class="mt-3">
                  {{ form.regularity.label_tag }}{{ form.frequency }}
               </div>
               {% if message.count == 0 %}
               <div class="mt-3">
                  {{ form.message.label_tag }}
               </div>
               <div class="alert alert-info">
                  Сообщения не обнаружены.
               </div>
               <a href="{% url 'mailings:create_message' %}" class="btn btn-primary">Добавить сообщение</a>
               {% else %}
               <div class="mt-3">
                  {{ form.message.label_tag }}{{ form.message }}
               </div>
               {% endif %}

               
               <button type="submit" name="save_mailing"   class="btn btn-success mt-3">
               {% if object %}
                  Сохранить
               {% else %}
                  Создать
               {% endif %}
               </button>
               {% if clients.count > 1 %}
               <a id="select-all-clients" type="submit" class="btn btn-primary custom-button mt-3">
                  Выбрать всех клиентов
               </a>
               {% endif %}
               {% if clients.count > 0 %}
                  <a href="{% url 'mailings:create_client' %}" class="btn btn-primary mt-3">Добавить клиента</a>
               {% endif %}
               <a href="{% url 'mailings:create_message' %}" class="btn btn-primary mt-3">Добавить сообщение</a>
                <a onclick="goBack()" class="btn btn-warning mt-3">Отмена</a>
                
               
               
                   

               
               
                  
               
            </form>
         </div>
      </div>
   </div>
</div>

<script>
   document.addEventListener("DOMContentLoaded", function () {
       const selectAllClientsButton = document.getElementById("select-all-clients");
       const clientCheckboxes = document.querySelectorAll('input[name="clients"]');

       selectAllClientsButton.addEventListener("click", function (event) {
           event.preventDefault();

           for (const checkbox of clientCheckboxes) {
               checkbox.checked = true;
           }
       });
   });
</script>

<script>
function goBack() {
  window.history.back();
}
</script>

<style>
   .custom-button {
   color: white !important;
   }
</style>
{% endblock %}

templates/mailings/mailing_list.html
{% extends 'index.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Рассылки</h1>
</div>
<div class="col-12 mb-3">
    <a class="btn btn-outline-primary col-12" href="{% url 'mailings:create_mailing' %}">Добавить рассылку</a>
</div>    
<div class="row text-center mt-3">
    {% for object in object_list %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Рассылка "{{ object.mail_subject }}"</h4>
            </div>
            <div class="card-body">
                <div class="card-text">Дата рассылки: {{ object.mailing_time }}.</div>
                <a href="{% url 'mailings:detail_mailing' object.pk %}" type="button"
                   class="btn btn-lg btn-block btn-outline-primary mt-3">Подробнее</a>
                <a href="{% url 'mailings:update_mailing' object.pk %}" type="button"
                   class="btn btn-lg btn-block btn-outline-warning mt-3">Изменить</a>
                <a href="{% url 'mailings:delete_mailing' object.pk %}" type="button"
                   class="btn btn-lg btn-block btn-outline-danger mt-3">Удалить</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/mailings/mailing_log_detail.html
{% extends 'index.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        {{ object }}
                    </h3>
                </div>
                <div class="card-body">
                    <p>
                        Дата и время попытки: {{ object.timestamp }}
                    </p>
                    <p>
                        Cтатус попытки: "{{ object.status }}"
                    </p>
                    {% if object.server_response %}
                    <p>
                        Ответ почтового сервера {{ object.server_response }}
                    </p>
                    {% endif %}
                </div>
                <div class="card-footer" style="display: flex; justify-content: space-between; align-items: center;">
                    <div class="card-text">Создатель: {{ object.user }}</div>
                    <div class="right-button">
                        <a onclick="goBack()" class="btn btn-warning mt-2">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
function goBack() {
  window.history.back();
}
</script>
{% endblock %}

templates/mailings/mailing_message.html
{% autoescape off %}
{{ object.mail_text }}
{% endblock %}
Mailing Service!
{% block reset_link %}
http://{{ domain }}
{% endautoescape %}

templates/mailings/message_confirm_delete.html
{% extends 'index.html' %}

{% block content %}
<div class="col-12">
    <div class="col-md-6 mx-auto">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Хотите удалить сообщение "{{ object.mail_subject }}"?</p>
                    <button type="submit" class="btn btn-danger">Подтвердить</button>
                    <a onclick="goBack()" class="btn btn-warning">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
function goBack() {
  window.history.back();
}


</script>
{% endblock %}

templates/mailings/messages_list.html
{% extends 'index.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Сообщения</h1>
</div>
<div class="col-12 mb-3">
    <a class="btn btn-outline-primary col-12" href="{% url 'mailings:create_message' %}">Добавить сообщение</a>
</div>
<div class="row text-center mt-3">
    {% for object in object_list %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Сообщение "{{ object.mail_subject }}"</h4>
            </div>
            <div class="card-body">
                   <div class="card-text">Текст: {{ object.mail_text }}.</div>
                
                <a href="{% url 'mailings:detail_message' object.pk %}" type="button"
                   class="btn btn-lg btn-block btn-outline-primary mt-3">Подробнее</a>
                <a href="{% url 'mailings:update_message' object.pk %}" type="button"
                   class="btn btn-lg btn-block btn-outline-warning mt-3">Изменить</a>
                <a href="{% url 'mailings:delete_message' object.pk %}" type="button"
                   class="btn btn-lg btn-block btn-outline-danger mt-3">Удалить</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}