cfg/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls', namespace='mailings')),
    path('', include('users.urls', namespace='users')),
    path('', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path

from mailings.views import CreateMailingView, ListMailingView, UpdateMailingView, DeleteMailingView, \
    DetailMailingView, CreateClientView, ListClientView, DeleteClientView, MailingLogListView, DeleteMailingLogView, \
    DetailMailingLogView, DetailClientView, UpdateClientView, CreateMessageView, ListMessageView, UpdateMessageView, \
    DeleteMessageView, DetailMessageView

app_name = 'mailings'

urlpatterns = [
    path('mailing/create', CreateMailingView.as_view(), name='create_mailing'),
    path('mailing/list', ListMailingView.as_view(), name='list_mailing'),
    path('mailing/update/<int:pk>/', UpdateMailingView.as_view(), name='update_mailing'),
    path('mailing/delete/<int:pk>/', DeleteMailingView.as_view(), name='delete_mailing'),
    path('mailing/detail/<int:pk>/', DetailMailingView.as_view(), name='detail_mailing'),

    path('client/create/', CreateClientView.as_view(), name='create_client'),
    path('client/list/', ListClientView.as_view(), name='list_client'),
    path('client/update/<int:pk>/', UpdateClientView.as_view(), name='update_client'),
    path('client/detail/<int:pk>/', DetailClientView.as_view(), name='detail_client'),
    path('client/delete/<int:pk>/', DeleteClientView.as_view(), name='delete_client'),

    path('message/create/', CreateMessageView.as_view(), name='create_message'),
    path('message/list/', ListMessageView.as_view(), name='list_message'),
    path('message/update/<int:pk>/', UpdateMessageView.as_view(), name='update_message'),
    path('message/delete/<int:pk>/', DeleteMessageView.as_view(), name='delete_message'),
    path('message/detail/<int:pk>/', DetailMessageView.as_view(), name='detail_message'),

    path('logs/', MailingLogListView.as_view(), name='mailing_logs_list'),
    path('logs/detail/<int:pk>/', DetailMailingLogView.as_view(), name='mailing_log_detail'),
    path('log/delete/<int:pk>/', DeleteMailingLogView.as_view(), name='delete_mailing_log'),
]

users/urls.py
from django.urls import path

from users.views import RegisterView, ResetView, ResetDoneView, EmailVerifyView, EmailVerifyDoneView, UserUpdateView, \
    LogoutView, LoginView, UsersListView

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', UserUpdateView.as_view(), name='user_form'),
    path('reset/', ResetView.as_view(), name='reset'),
    path('done/', ResetDoneView.as_view(), name='done'),
    path('register/', RegisterView.as_view(), name='register'),
    path('email_verify/', EmailVerifyView.as_view(), name='email_verify'),
    path('email_verify_done/<uidb64>/<token>/', EmailVerifyDoneView.as_view(), name='email_verify_done'),
    path('list/', UsersListView.as_view(), name='users'),
]

templates/includes/inc_main_menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Mail Service</h5>
    <nav class="ms-auto">
        {% if user.is_superuser %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'admin:index' %}">Админка</a>
        {% endif %}
        {% if not user.is_authenticated %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
        {% else %}
            {% if not user.is_email_active %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:email_verify' %}">Подтвердить Email</a>
            {% endif %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:user_form' %}">Профиль</a>
        {% endif %}
        <a class="p-2 btn btn-outline-primary" href="/">Главная</a>
        {% if user.is_authenticated %}
            {% if not user.is_superuser %}
               <a class="p-2 btn btn-outline-primary" href="{% url 'mailings:create_mailing' %}">Создать рассылку</a>
               <a class="p-2 btn btn-outline-primary" href="{% url 'mailings:list_mailing' %}">Список рассылок</a>
               <a class="p-2 btn btn-outline-primary" href="{% url 'mailings:list_client' %}">Список клиентов</a>
                <a class="p-2 btn btn-outline-primary" href="{% url 'mailings:list_messages' %}">Список писем</a>
            {% endif %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'mailings:mailing_logs_list' %}">Логи рассылок</a>
        {% endif %}
        {% if user.is_authenticated %}
    <form method="post" action="{% url 'users:logout' %}">
            {% csrf_token %}
            <button class="p-2 btn btn-outline-primary">Выйти</button>
            </form>
    {% endif %}
    </nav>
</div>