blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView
from django.views.decorators.cache import cache_page
app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='home'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='view'),
]

cfg/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls', namespace='mailings')),
    path('', include('users.urls', namespace='users')),
    path('', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from PIL import Image

# Create your models here.
NULLABLE = {'null': True, 'blank': True}


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    overview = models.TextField(max_length=350, verbose_name='содержимое', **NULLABLE)
    preview = models.ImageField(default='placeholder.png', upload_to='', verbose_name='изображение', **NULLABLE)
    date_of_creation = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    view_counter = models.IntegerField(default=0, verbose_name='кол-во просмотров')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.preview:
            image = Image.open(self.preview.path)
            target_size = (300, 300)
            image.thumbnail(target_size)
            image.save(self.preview.path)

blog/views.py
from django.shortcuts import render

# Create your views here.
import random

from django.db.models import Func
from django.views.generic import DetailView, ListView

from blog.models import Blog
from mailings.models import Mailing, Client


# Create your views here.
class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_counter += 1
        self.object.save()
        return self.object


class RandomFunc(Func):
    function = 'RANDOM'


class BlogListView(ListView):
    model = Blog
    template_name = 'blog/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mailings = len(Mailing.objects.all())
        mailings_is_active = len(Mailing.objects.filter(is_active=True))
        unique_clients_count = Client.objects.values('email').distinct().count()
        context['mailings'] = mailings
        context['mailings_is_active'] = mailings_is_active
        context['unique_clients_count'] = unique_clients_count
        return context

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = list(queryset)
        random.shuffle(queryset)
        return queryset[:3]

templates/blog/blog_detail.html
{% extends 'index.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Материал "{{ object.title }}"
                    </h3>
                </div>
                <div class="card-body">
                    <p>
                        {{ object.overview }}
                    </p>
                </div>
                <div class="card-footer" style="display: flex; justify-content: space-between; align-items: center;">
                    <div>
                        Просмотры: {{ object.view_counter }}
                    </div>
                    <div class="right-button">
                        <a onclick="goBack()" class="btn btn-warning mt-2">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
function goBack() {
  window.history.back();
}
</script>
{% endblock %}tml>

templates/blog/dashboard.html
{% extends 'index.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Mail Service</h1>
</div>
<div class="col-12">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">Статистика</h4>
        </div>
        <div class="card-body">
            <div class="card-text">
                Количество рассылок всего: {{ mailings }}
            </div>
            <div class="card-text">
                Количество активных рассылок: {{ mailings_is_active }}
            </div>
            <div>
                Количество уникальных клиентов для рассылок: {{ unique_clients_count }}
            </div>
        </div>
        <div class="card-footer"></div>
    </div>
</div>
<div class="row text-center">
{% for object in object_list %}
<div class="col-4">
    <div class="card mb-4 box-shadow">
        <div class="card-header text-center">
            <h4 class="my-0 font-weight-normal">Статья "{{ object.title }}"</h4>
        </div>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:view' object.pk %}">Подробнее</a>
        <div class="card-footer">
            <div class="card-text">Дата создания: {{ object.date_of_creation }}</div>
        </div>
    </div>
</div>
{% endfor %}
</div>
{% endblock %}