cfg/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls', namespace='mailings')),
    path('', include('users.urls', namespace='users')),
    path('', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import RegisterView, ResetView, ResetDoneView, EmailVerifyView, EmailVerifyDoneView, UserUpdateView, \
    LogoutView, LoginView, UsersListView

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', UserUpdateView.as_view(), name='user_form'),
    path('reset/', ResetView.as_view(), name='reset'),
    path('done/', ResetDoneView.as_view(), name='done'),
    path('register/', RegisterView.as_view(), name='register'),
    path('email_verify/', EmailVerifyView.as_view(), name='email_verify'),
    path('email_verify_done/<uidb64>/<token>/', EmailVerifyDoneView.as_view(), name='email_verify_done'),
    path('list/', UsersListView.as_view(), name='users'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from mailings.models import NULLABLE


# Create your models here.
class User(AbstractUser):

    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    is_email_active = models.BooleanField(default=False, verbose_name='верификация по почте')
    is_active = models.BooleanField(default=True, verbose_name='признак активности')

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

        permissions = [
            (
                'view_all_clients',
                'can view all clients',
            ),
            (
                'set_active',
                'can activate clients',
            ),
        ]

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.urls import reverse_lazy

from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class PasswordAltResetForm(forms.Form):
    email = forms.EmailField(
        label="Укажите вашу электронную почту",
        max_length=254,
        widget=forms.EmailInput(attrs={"autocomplete": "email"}),
    )


class UserForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.conf import settings
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import PasswordResetDoneView, LogoutView as BaseLogoutView, LoginView as BaseLoginView
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ValidationError
from django.core.mail import EmailMessage, get_connection
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.generic import CreateView, FormView, UpdateView, ListView

from users.forms import UserRegisterForm, PasswordAltResetForm, UserForm
from users.models import User


# Create your views here.
class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')


class LogoutView(BaseLogoutView):
    next_page = reverse_lazy('users:login')
    pass


class LoginView(BaseLoginView):
    template_name = 'users/login.html'
    next_page = reverse_lazy('blog:home')


class ResetView(FormView):
    model = User
    form_class = PasswordAltResetForm
    email_template_name = 'users/users/reset_email.html'
    template_name = 'users/reset_password.html'
    success_url = reverse_lazy('users:done')
    token_generator = default_token_generator

    def get(self, request, **kwargs):
        return render(request, self.template_name, {'form': self.form_class})

    @staticmethod
    def send_mail_for_reset(request, email, new_password):
        current_site = get_current_site(request)
        context = {
            'domain': current_site.domain,
            'new_password': new_password
        }
        message = render_to_string('users/reset_email.html', context=context)
        email = EmailMessage(
            'Восстановление пароля',
            message,
            to=[email],
            from_email=settings.EMAIL_HOST_USER
        )
        email.send()

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            user = self.model.objects.get(email=email)
            if user:
                new_password = self.token_generator.make_token(user)[:10]
                user.set_password(new_password)
                user.save()
                self.send_mail_for_reset(request, email, new_password)
                return redirect(self.success_url)
            else:
                return render(request, 'users/email_verify_unsuccessful.html')


class ResetDoneView(PasswordResetDoneView):
    template_name = 'users/reset_done.html'
    title = "Сообщение отправлено!"


class UserUpdateView(UpdateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('blog:home')

    def get_object(self, queryset=None):
        return self.request.user


class UsersListView(PermissionRequiredMixin, ListView):
    model = User
    permission_required = "view_all_users"
    template_name = "users/users.html"



class EmailVerifyView(FormView):
    model = User
    email_template_name = 'users/email_verify_message.html'
    template_name = 'users/email_verify_confirm.html'
    success_url = 'users/email_verify_sended.html'
    token_generator = default_token_generator

    @staticmethod
    def send_mail_for_verify(request, user, token_generator):
        current_site = get_current_site(request)
        context = {
            'user': user,
            'domain': current_site.domain,
            "uid": urlsafe_base64_encode(force_bytes(user.pk)),
            "token": token_generator.make_token(user),
        }
        message = render_to_string('users/email_verify_message.html', context=context)
        email = EmailMessage("Подтверждение почты",
                             message,
                             to=[user.email],
                             from_email=settings.EMAIL_HOST_USER)
        email.send()



    def get(self, request, **kwargs):
           return render(request, self.template_name)

    def post(self, request, **kwargs):
        user = request.user
        self.send_mail_for_verify(request, user, self.token_generator)
        return render(request, self.success_url)


class EmailVerifyDoneView(View):
    model = User
    template_name = 'users/email_verify_done.html'
    unsuccessful_template_name = 'users/email_verify_unsuccessful.html'
    anonim_template_name = 'users/email_verify_anonim.html'
    token_generator = default_token_generator

    @staticmethod
    def get_user(model, uidb64):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = model.objects.get(pk=uid)
        except (
                TypeError,
                ValueError,
                OverflowError,
                model.DoesNotExist,
                ValidationError,
        ):
            user = None
        return user

    def get(self, request, uidb64, token, **kwargs):
        user = request.user
        print(user.pk)

        if user.pk is None:
            return render(request, self.anonim_template_name)

        user_for_email_activation = self.get_user(self.model, uidb64)
        token_for_email_activation = self.token_generator.check_token(user, token)

        if user == user_for_email_activation and token_for_email_activation:
            user.is_email_active = True
            user.save()
            return render(request, self.template_name)
        else:
            return render(request, self.unsuccessful_template_name)

templates/users/email_verify_anonim.html
{% extends 'index.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Подтверждение электронной почты
                    </h3>
                </div>
                <div class="card-body">
                    Для подтверждения электронной почты, необходимо войти.
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

templates/users/email_verify_confirm.html
{% extends 'index.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Подтверждение электронной почты
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                     <div class="card-text">
                    Чтобы отправить сообщение с ссылкой для подтверждения электронной почты, нажмите кнопку ниже.
                    </div>
                    <button type="submit" class="btn btn-primary mt-3">
                        Отправить
                    </button>
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

templates/users/email_verify_done.html
{% extends 'index.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Подтверждение электронной почты
                    </h3>
                </div>
                <div class="card-body">
                    Электронная почта подтверждена!
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

templates/users/email_verify_message.html
{% autoescape off %}
Добрый день! Пожалуйста, перейдите по ссылке ниже для подтверждения электронной почты:
{% block reset_link %}
http://{{ domain }}{% url 'users:email_verify_done' uidb64=uid token=token %}
{% endblock %}
Mail Service!
{% endautoescape %}

templates/users/email_verify_sended.html
{% extends 'index.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Подтверждение электронной почты
                    </h3>
                </div>
                <div class="card-body">
                    Ссылка для подтверждения Email адреса отправлена на вашу электронную почту!
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

templates/users/email_verify_unsuccessful.html
{% extends 'index.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Подтверждение электронной почты
                    </h3>
                </div>
                <div class="card-body">
                    Ссылка повреждена, подтвердить электронную почту не удалось.
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

templates/users/login.html
{% extends 'index.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Вход
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Войти</button>
                    <a href="{% url 'users:reset' %}" type="submit" class="btn btn-primary">Забыл(а) пароль</a>
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

templates/users/register.html
{% extends 'index.html' %}
{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Регистрация
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

templates/users/reset_done.html
{% extends 'index.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Восстановление пароля
                    </h3>
                </div>
                <div class="card-body">
                    Ссылка для изменения пароля отправлена на вашу электронную почту!
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

templates/users/reset_email.html
{% autoescape off %}
Добрый день! Вот ваш новый пароль: {{ new_password }}
Пожалуйста, перейдите по ссылке ниже для того, чтобы войти:
{% block link %}
http://{{ domain }}{% url 'users:login' %}
{% endblock %}
Mail Service!
{% endautoescape %}

templates/users/reset_password.html
{% extends 'index.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Восстановление пароля
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Отправить</button>
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

templates/users/user_form.html
{% extends 'index.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    Мой профиль
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/users.html
{% extends 'index.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Пользователи</h1>
</div>

<div class="row text-center mt-3">
    {% for object in object_list %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Юзер "{{ object.email }}"</h4>
            </div>
            <div class="card-body">
                   <div class="card-text">Имя: {{ object.first_name }} {{ object.last_name }}.</div>
            </div>
            <div class="card-body">
                
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}